config/routes.rb
Rails.application.routes.draw do
  resources :sells
  resources :books
  get "dashboard/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  validates_presence_of :name, :price

  has_many :sells
end

app/models/sell.rb
class Sell < ApplicationRecord
  DAYS = %W[MONDAY TUESDAY WEDNESDAY THURSDAY FRIDAY SATURDAY SUNDAY].freeze

  validates :quantity, presence: true
  validates :day, inclusion: {in: DAYS}, presence: true

  belongs_to :book

  before_save :calc_total

  private

  def calc_total
    self.total = quantity * book.price
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      @book.broadcast_append_to(
        'bookstore_channel',
        partial: 'dashboard/charts/books/chart',
        locals: {book: @book},
        target: 'books_charts'
      )
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def book_params
    params.require(:book).permit(:name, :price)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/sells_controller.rb
class SellsController < ApplicationController
  def new
    @sell = Sell.new
  end

  def create
    @sell = Sell.new(sell_params)

    if @sell.save
      @sell.broadcast_replace_to(
        'bookstore_channel',
        partial: 'dashboard/charts/days/chart',
        target: 'days_chart'
      )

      @sell.broadcast_replace_to(
        'bookstore_channel',
        partial: 'dashboard/charts/revenue/chart',
        target: 'revenue_chart'
      )

      @sell.broadcast_replace_to(
        'bookstore_channel',
        partial: 'dashboard/charts/books/chart',
        locals: {book: @sell.book},
        target: "book_#{@sell.book_id}_chart"
      )
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def sell_params
    params.require(:sell).permit(:quantity, :book_id, :day)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def latest_sells(book)
    book.sells.pluck(:quantity)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/sells_helper.rb
module SellsHelper
  def sells_per_day
    sells = Sell.group(:day).sum(:quantity)
    sells_ordered = Sell::DAYS.map { |day| sells[day] || 0 }

    [Sell::DAYS, sells_ordered]
  end

  def revenue_from_sells
    sells = Sell.joins(:book).group(:name).sum(:total)
    totals = sells.values.map { |t| t.round(2) }

    [sells.keys, totals]
  end
end

app/views/books/_form.html.erb
<%= turbo_frame_tag 'new_record_component' do %>
  <div>
    <%= form_with model: book, class: 'flex w-full items-center gap-2',
      data: {controller: 'forms', action: 'submit->forms#resetComponent'} do |f| %>

      <% if book.errors.any? %>
        <div class="text-red-500 errors">
          <%= book.errors.map { |e| e.full_message }.join(', ') %>
        </div>
      <% end %>

      <div class="flex items-center gap-2">
        <%= f.label :name, class: 'font-semibold text-white' %>
        <%= f.text_field :name, class: 'font-semibold rounded p-2 text-xs' %>
      </div>

      <div class="flex items-center gap-2">
        <%= f.label :price, class: 'font-semibold text-white' %>
        <%= f.number_field :price, in: (1.0..100.0), step: :any,
          class: 'font-semibold rounded p-2 text-xs' %>
      </div>

      <div class="flex items-center gap-2 ml-5 justify-end">
        <%= f.submit class: 'font-semibold p-2 bg-sky-600 text-sm text-white rounded cursor-pointer' %>

        <%= link_to 'Cancel', :back,
          class: 'font-semibold p-2 bg-red-600 text-sm text-white rounded' %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/books/new.html.erb
<%= render 'form', book: @book %>

app/views/dashboard/charts/books/_books.html.erb
<section class="flex w-full flex-col p-2" id="books_charts">
  <h3 class="text-white font-bold text-lg">Sells by book</h3>

  <% Book.all.each do |book| %>
    <%= render 'dashboard/charts/books/chart', book: book %>
  <% end %>
</section>

app/views/dashboard/charts/books/_chart.html.erb
<div data-controller="books" data-book-sells="<%= latest_sells(book) %>"
  data-book-id="<%= book.id %>" class="text-white" id="book_<%= book.id %>_chart">

  <h3 class="text-white text-center mt-2"><%= book.name %></h3>

  <canvas id="bookChart-<%= book.id %>" style="width:100%;max-width:700px"></canvas>
</div>

app/views/dashboard/charts/days/_chart.html.erb
<div data-controller="days" data-days-sells="<%= sells_per_day %>" id="days_chart">
  <canvas id="daysSells" style="width:100%;max-width:700px"></canvas>
</div>

app/views/dashboard/charts/days/_days.html.erb
<section class="flex w-full flex-col p-2">
  <h3 class="text-white font-bold text-lg">Sells per day</h3>

  <%= render 'dashboard/charts/days/chart' %>
</section>

app/views/dashboard/charts/revenue/_chart.html.erb
<div data-controller="revenue" data-revenue-sells="<%= revenue_from_sells %>" id="revenue_chart">
  <canvas id="revenueSells" style="width:100%;max-width:700px"></canvas>

  <div class="bg-white rounded flex flex-col my-5 mx-3 p-2">
    <h5 class="font-bold text-center text-xl mt-2">Sells by book</h5>

    <table class="my-5">
      <thead>
        <th class="border-2">ID</th>
        <th class="border-2">Name</th>
        <th class="border-2">Revenue</th>
      </thead>

      <tbody>
        <% Book.joins(:sells).group(:id, :name).sum(:total).each do |(id, name), revenue| %>
          <tr>
            <td class="border-2 text-center"><%= id %></td>
            <td class="border-2 text-center"><%= name %></td>
            <td class="border-2 text-center"><%= number_to_currency(revenue) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <h3 class="font-semibold">Total: <%= number_to_currency(Sell.sum(:total)) %></h3>
  </div>
</div>

app/views/dashboard/charts/revenue/_revenue.html.erb
<section class="flex w-full flex-col p-2">
  <h3 class="text-white font-bold text-lg">Revenue</h3>

  <%= render 'dashboard/charts/revenue/chart' %>
</section>

app/views/dashboard/index.html.erb
<%= turbo_stream_from 'bookstore_channel' %>

<main class="flex flex-col bg-black">
  <%= render 'shared/navbar' %>

  <section class="flex flex-col items-center justify-center w-full mt-20 mb-5">
    <div class="flex flex-col items-center">
      <h1 class="font-bold text-4xl text-white my-5">The Bookstore App</h1>
    </div>

    <div class="flex gap-5 border-4 border-gray-200 w-full min-h-screen">
      <%= render 'dashboard/charts/days/days' %>
      <%= render 'dashboard/charts/revenue/revenue' %>
      <%= render 'dashboard/charts/books/books' %>
    </div>
  </section>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Bookstore" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>


    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sells/_form.html.erb
<%= turbo_frame_tag 'new_record_component' do %>
  <div>
    <%= form_with model: sell, class: 'flex w-full items-center gap-2' do |f| %>

      <% if sell.errors.any? %>
        <div class="text-red-500 errors">
          <%= sell.errors.map { |e| e.full_message }.join(', ') %>
        </div>
      <% end %>

      <div class="flex items-center gap-2">
        <%= f.label :book_id, class: 'font-semibold text-white' %>

        <%= f.collection_select :book_id, Book.order(:name), :id, :name, {include_blank: true},
          class: 'font-semibold rounded p-2 text-xs' %>
      </div>

      <div class="flex items-center gap-2">
        <%= f.label :day, class: 'font-semibold text-white' %>

        <%= f.select :day, Sell::DAYS, {include_blank:true},
          class: 'font-semibold rounded p-2 text-xs' %>
      </div>

      <div class="flex items-center gap-2">
        <%= f.label :quantity, class: 'font-semibold text-white' %>
        <%= f.number_field :quantity, in: (1..999), class: 'font-semibold rounded p-2 text-xs' %>
      </div>

      <div class="flex items-center gap-2 ml-5 justify-end">
        <%= f.submit class: 'font-semibold p-2 bg-sky-600 text-sm text-white rounded cursor-pointer' %>

        <%= link_to 'Cancel', :back,
          class: 'font-semibold p-2 bg-red-600 text-sm text-white rounded' %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/sells/new.html.erb
<%= render 'form', sell: @sell %>

app/views/shared/_navbar.html.erb
<nav class="w-full flex bg-black items-center p-5 justify-between fixed">
  <div class="flex gap-5 items-center">
    <%= image_tag('sells.png', class: 'w-12') %>
    <h3 class="font-bold text-lg text-white">The Bookstore App</h3>
  </div>

  <%= turbo_frame_tag 'new_record_component', class: 'flex gap-5' do %>
    <%= link_to 'Add sell', new_sell_path, id: 'sell_link',
      class: 'text-white font-semibold text-sm text-center bg-green-700 rounded px-4 py-2' %>

    <%= link_to 'Add a new book', new_book_path, id: 'book_link',
      class: 'text-white font-semibold text-sm text-center bg-sky-700 rounded px-4 py-2' %>
  <% end %>
</nav>